name: Angular

env:
  azure-webapp-name: tickets.ui
  bundle-name: angular-app
  node-version: 16.15.0

on:
  push:
	branches:
	  - main
  pull_request: {}
  workflow_dispatch: {}
	
jobs:
lint:
    name: Lint (PR)
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

build:
    name: Build
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh
	
	steps:
	- uses: actions/checkout@v2
	
	- name: Set up Node.js ${{ env.node-version }}
	  uses: actions/setup-node@v2
      with:
        node-version: 16.15.0
        cache: yarn
  - name: Install dependencies
  run: yarn install

  - name: Build app
    run: yarn build
		
	- name: Upload WebApp package
    uses: actions/upload-artifact@v2
      with:
        name: ${{ env.bundle-name }}
        path: dist/Tickets.UI
        if-no-files-found: error

test:
    name: Test
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cahce: yarn
      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn ci:test
